// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	TokenHash []byte             `db:"token_hash" json:"token_hash"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BookMetadatum struct {
	SourceID  pgtype.UUID        `db:"source_id" json:"source_id"`
	Isbn10    pgtype.Text        `db:"isbn_10" json:"isbn_10"`
	Isbn13    pgtype.Text        `db:"isbn_13" json:"isbn_13"`
	Publisher pgtype.Text        `db:"publisher" json:"publisher"`
	PageCount pgtype.Int4        `db:"page_count" json:"page_count"`
	Language  pgtype.Text        `db:"language" json:"language"`
	CoverUrl  pgtype.Text        `db:"cover_url" json:"cover_url"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Collection struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	IsPublic    pgtype.Bool        `db:"is_public" json:"is_public"`
	SourceIds   []byte             `db:"source_ids" json:"source_ids"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Contributor struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Bio       pgtype.Text        `db:"bio" json:"bio"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Note struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	SourceID    pgtype.UUID        `db:"source_id" json:"source_id"`
	Content     string             `db:"content" json:"content"`
	ContentType string             `db:"content_type" json:"content_type"`
	IsPublic    pgtype.Bool        `db:"is_public" json:"is_public"`
	Annotations []byte             `db:"annotations" json:"annotations"`
	Tags        []byte             `db:"tags" json:"tags"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Outbox struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   pgtype.UUID        `db:"aggregate_id" json:"aggregate_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	Payload       []byte             `db:"payload" json:"payload"`
	Published     pgtype.Bool        `db:"published" json:"published"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

type Profile struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	DisplayName   pgtype.Text        `db:"display_name" json:"display_name"`
	Bio           pgtype.Text        `db:"bio" json:"bio"`
	PublicProfile pgtype.Bool        `db:"public_profile" json:"public_profile"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RefreshToken struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash         []byte             `db:"token_hash" json:"token_hash"`
	FamilyID          pgtype.UUID        `db:"family_id" json:"family_id"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	ReplacedByTokenID pgtype.UUID        `db:"replaced_by_token_id" json:"replaced_by_token_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Review struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	SourceID  pgtype.UUID        `db:"source_id" json:"source_id"`
	Rating    pgtype.Int4        `db:"rating" json:"rating"`
	Content   pgtype.Text        `db:"content" json:"content"`
	IsPublic  pgtype.Bool        `db:"is_public" json:"is_public"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Source struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Subtitle    pgtype.Text        `db:"subtitle" json:"subtitle"`
	Type        string             `db:"type" json:"type"`
	Description pgtype.Text        `db:"description" json:"description"`
	Publisher   pgtype.Text        `db:"publisher" json:"publisher"`
	Isbn        pgtype.Text        `db:"isbn" json:"isbn"`
	Doi         pgtype.Text        `db:"doi" json:"doi"`
	Url         pgtype.Text        `db:"url" json:"url"`
	ExternalID  pgtype.Text        `db:"external_id" json:"external_id"`
	Tags        []byte             `db:"tags" json:"tags"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SourceContributor struct {
	SourceID      pgtype.UUID        `db:"source_id" json:"source_id"`
	ContributorID pgtype.UUID        `db:"contributor_id" json:"contributor_id"`
	Role          string             `db:"role" json:"role"`
	Position      int32              `db:"position" json:"position"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Tag struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Email           string             `db:"email" json:"email"`
	Username        string             `db:"username" json:"username"`
	PasswordHash    pgtype.Text        `db:"password_hash" json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OidcIssuer      pgtype.Text        `db:"oidc_issuer" json:"oidc_issuer"`
	OidcSubject     pgtype.Text        `db:"oidc_subject" json:"oidc_subject"`
}

type UserLibraryItem struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	SourceID      pgtype.UUID        `db:"source_id" json:"source_id"`
	Status        string             `db:"status" json:"status"`
	ProgressValue pgtype.Int4        `db:"progress_value" json:"progress_value"`
	ProgressUnit  pgtype.Text        `db:"progress_unit" json:"progress_unit"`
	Visibility    string             `db:"visibility" json:"visibility"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
